var name;
var age;
name="Sufia<br/>";
age=23;
document.write(name);
document.write(age);
var num=12;
console.log(typeof(num));
var num="123";
console.log(typeof(num));
num=parseInt(num);
console.log(typeof(num));
console.log(Number("123"))
var fristName="sabbir";
var LastName="Ahmad<br/>";
var fullName= fristName + LastName;
document.write(fullName);
var text=prompt("Enter your Country name:");
document.write("Number of character "+ text.length);
var text="southAfrica<br/>";
text=text.charAt(3);
var text="Banladesh";
document.write(text);
text=text.toUpperCase(text);
document.write(next);
